# Max Wiegant
# 2-19-17
# Make Peace, not Bugs
# ( make sure tabs are used )

CC = g++
DEBUG = -g
CFLAGS = -c -std=c++11
LFLAGS = -std=c++11

SOURCE = PA1/
#SOURCE_1 = 1_gaussian_smoothing/
#SOURCE_2 = 2_edge_detection/
# SOURCE_3 = /

pa1 : menu.cpp
	$(CC) $(LFLAGS) menu.cpp -o pa1


### Gaussian Smoothing


# todo

clean:
	\rm *.o pa1